# Preface

Welcome to this introduction to Jupyter Notebook. This is an interactive web-based programming platform which allows you, the student, to write and execute Python code from the comfort of your web browser.

Do not despair if you don't have prior experience with Python. Since you most certainly have C and MATLAB experience from previous courses, picking up Python is very straightforward. This assignment aims to get you familiar with the Python language as well as the Jupyter Notebook interface.

In [6]:
print('When you run this code block, the printed outputs should be shown below the code block.')
print('Hello World!')

When you run this code block, the printed outputs should be shown below the code block.
Hello World!


You may also change the content of code blocks:

In [7]:
print('Who are you?')
print('I\'m [insert your name here!]')

Who are you?
I'm [insert your name here!]


If you run code that contains errors, descriptive debugging messages would be shown below the code block. Run the following and have a look yourself. Then fix the code (it's missing a closing parenthesis at the end) and run it again.

In [8]:
print('This code block contains errors. Please try to fix me!')

This code block contains errors. Please try to fix me!


# Introduction to Python

First, we try our best to bridge the gap between Python and languages that you've been exposed to in past courses. Note that although Python is an object-oriented languaged (i.e. you may create class structures with Python), we will stick with functional programming in Jupyter Notebook assignments to keep things simple.

## Declaring and Using Variables

Python, like MATLAB, is a dynamically typed language. Variable declaration as simple as:

In [11]:
# declare a few variables
some_int = 42
some_float = 3.14159
some_str = 'Hello World'

# by the way, you may add comments by using the hash (#) symbol

The variables are accessed by name. Here, we print them with the `print()` function in a number of ways. Read the comments above each print statement to see what is done!

In [13]:
# 0. straightforward variable printing
print(some_str)

# 1. printing with mixed strings and variable
print('1. The content of some_int is ', some_int, ', but this is a rather cumbersome syntax.')

# 2. printing with mixed strings and variable via formatted string literal (a.k.a. f-string)
print(f'2. The content of some_int is {some_int}. This concise string formatting is often referred to as f-string (note the \'f\' prefix in the print statement).')

# 3. floats can also be formatted by {var_name:string_width.precision}
print(f'3. The content of some_float, with precision formatting, is {some_float:7.5}')

Hello World
1. The content of some_int is  42 , but this is a rather cumbersome syntax.
2. The content of some_int is 42. This concise string formatting is often referred to as f-string (note the 'f' prefix in the print statement).
3. The content of some_float, with precision formatting, is  3.1416


You may refer to the official Python documentation for more [details and examples](https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings) on the usage of f-string.

Python lists are also very straightforward:

In [14]:
# reset the Python environment
%reset -f

# 1D list
one_d_list = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

# 2D list
two_d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# access specific elements
# note that whereas MATLAB indices start at 1, Python indices start at 0
print('On the 1D list...')
print(f'Print the element at index 0: {one_d_list[0]}')
print(f'Print elements at indices 2 to 5 (excluding 5): {one_d_list[2:5]}')
print(f'Print the last element: {one_d_list[-1]}')
print(f'Print elements 5 till the end: {one_d_list[5:]}')
      

print('\nOn the 2D list...')
print(f'Print a specific element: {two_d_list[1][2]}')
print(f'Print the first row: {two_d_list[0]}')

On the 1D list...
Print the element at index 0: 0
Print elements at indices 2 to 5 (excluding 5): [1, 2, 3]
Print the last element: 55
Print elements 5 till the end: [5, 8, 13, 21, 34, 55]

On the 2D list...
Print a specific element: 6
Print the first row: [1, 2, 3]


However, Python lists are not meant for mathematical operations...

In [15]:
print('Can we just treat lists like vectors and perform a vector summation?')

a = [1,2,3]
b = [4,5,6]
print(f'a = {a}')
print(f'b = {b}')
print(f'a+b = {a+b}')

print('\na+b merely concatenated the lists, but we want vector summation!')

Can we just treat lists like vectors and perform a vector summation?
a = [1, 2, 3]
b = [4, 5, 6]
a+b = [1, 2, 3, 4, 5, 6]

a+b merely concatenated the lists, but we want vector summation!


NumPy to the rescue. NumPy is a mathematical library that provides many essential numerical computation features for Python. You may import it by `import numpy` and access its functions by `numpy.function_name()`. You may also save some keystrokes by importing it with an alias, e.g. `import numpy as np` and access its functions by `np.function_name()`. Here are some examples:

In [16]:
# reset the Python environment
%reset -f

import numpy as np

print('Vector summation...')

a = np.array([1,2,3])
b = np.array([4,5,6])
absum = a + b  # this line sums the vectors and stores them in the variable absum

print(f'a = {a}')
print(f'b = {b}')
print(f'a+b = {absum}')
print('Success!\n')

print('Matrix vector multiplication...')

M = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1,3,5])
mvprod = np.inner(M, v)  # this line computes the inner product of vectors M and v and stores them in mvprod

print(f'M = \n{M}')
print(f'v = {v}')
print(f'Mv inner product = {mvprod}')
print('Success!')

Vector summation...
a = [1 2 3]
b = [4 5 6]
a+b = [5 7 9]
Success!

Matrix vector multiplication...
M = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
v = [1 3 5]
Mv inner product = [22 49 76]
Success!


We will drop hints and useful NumPy usage references as needed in future Jupyter Notebook assignments, so don't worry if all this is very new to you.

## Python Conditions and Loops

### if, else, elif

The following examples illustrate the syntax of conditional blocks. The body of `if` statements need to be indented. Unindenting indicates the end of the conditional body.

In [17]:
# reset the Python environment
%reset -f

a = 4
b = 2

print(f'Compare the values of a={a} and b={b}...')

if a > b:
    # code that will run inside an if block must be indented
    print('a is greater than b')
elif a == b:
    # elif is equivalent to "else if" in C and "elseif" in MATLAB
    print('a equals b')
else:
    print('a is less than b')
    
# once you've unindented, the conditional block ends
print('The conditional block has ended, this statement gets printed regardless.')

Compare the values of a=4 and b=2...
a is greater than b
The conditional block has ended, this statement gets printed regardless.


### for loops

Here's how you create for loops:

In [18]:
# reset the Python environment
%reset -f

print('The range() function creates a sequence of numbers. If only a single parameter, N, is provided, '
     'the sequence 0 to N-1 consisting of N numbers would be created.')

print('Here, the for loop iterates through the sequence generated by range(5), assigns the value to variable '
      'i, and prints it.')

# for loop
for i in range(5):
    print(i)
    
print('\nThis time, the loop iterates through the sequence generated by range(0,50,10) and prints it.')

for i in range(0,50,10):
    print(i)

The range() function creates a sequence of numbers. If only a single parameter, N, is provided, the sequence 0 to N-1 consisting of N numbers would be created.
Here, the for loop iterates through the sequence generated by range(5), assigns the value to variable i, and prints it.
0
1
2
3
4

This time, the loop iterates through the sequence generated by range(0,50,10) and prints it.
0
10
20
30
40


Please refer to the official `range()` [usage reference](https://docs.python.org/3.3/library/stdtypes.html?highlight=range#range) for helpful examples.

## Declaring and Calling Functions

In Python, functions are declared with the `def` keyword:

In [19]:
# reset the Python environment
%reset -f

# a simple Python function that takes no input parameters and doesn't return anything
def some_func():
    # contents of a function must be indented
    print('some_func has been called')
    
# a Python function that takes two input parameters
# this time, we also include a docstring which provides documentaiton for this function
def another_func(param1, param2):
    '''
    Prints the type and value of the two input parameters.
    
    Parameters:
        param1: Some parameter
        param2: Another parameter
    '''
    print(f'another_func has been called.')
    print(f'param1 is of type {type(param1)} with value {param1}')
    print(f'param2 is of type {type(param2)} with value {param2}')
    
# call the functions
some_func()
another_func(42, 3.14)

some_func has been called
another_func has been called.
param1 is of type <class 'int'> with value 42
param2 is of type <class 'float'> with value 3.14


---
# Exercises

Exercises found in Jupyter Notebooks in this course are are designed to provide useful practice and intuition, and are ungraded. However, quizzes and assessment tests may test on such concepts.

Do not confuse these exercises with JN Mini Quizzes on Canvas, those are graded.

## Problem 1

Write a function that computes the area of a circle using the provided radius, $r$, rounded to 2 decimal places.

You can assume that $r > 0$.

Hints:
* Use `np.pi` to get the $\pi$ constant, e.g. `circumference = 2 * np.pi * r`.
* The exponent operator in Python is `**`, e.g. $x^3$ can be represented by `x**3`.
* Use the function `np.around` to round numbers ([doc](https://numpy.org/doc/stable/reference/generated/numpy.around.html)).

In [31]:
# reset the Python environment
%reset -f

import numpy as np

def area_of_circ(r):
    '''
    Return the area of a circle with the provided radius.
    
    Parameters:
        r: radius of the circle
    
    Returns:
        Area of the circle rounded to 2 decimal places.
    '''
    ### implement the function
    return np.around(np.pi * r**2, 2)

Your function should return `78.54` for $r = 5$. Check below:

In [32]:
area_of_circ(5)

78.54

---
## Problem 2

A Fibonacci sequence is a sequence of Fibonacci numbers, $F_n$, where each number is the sum of the two preceding ones. The first two Fibonacci numbers are set to be $F_0 = 0$ and $F_1 = 1$, with subsequent Fibonacci numbers given by $F_n = F_{n-1} + F_{n-2}$. The beginning of the sequence is:

$0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...$

See the [Wikipedia page](https://en.wikipedia.org/wiki/Fibonacci_number) on it to learn more.

For this problem, generate a Fibonacci sequence of the specified length, $n$, as a list of integers. You can assume that $n \geq 1$. Use Python's built-in list type, do not use a numpy array.

Hints:
* Declare an empty list by `some_list = []`.
* Append an item to a list by `some_list.append(42)`.

In [37]:
# reset the Python environment
%reset -f

def fibonacci_seq(n):
    '''
    Return a Fibonacci sequence of the specified length.
    
    Parameters:
        n: the length of the Fibonacci sequence
        
    Returns:
        A Fibonacci sequence of length n.
    '''
    ### implement the function
    fseq = []
    for i in range(n):
        if i == 0:
            fseq.append(0)
        elif i == 1:
            fseq.append(1)
        else:
            fseq.append(fseq[i-1] + fseq[i-2])
    
    return fseq

Your function should return `[0, 1, 1, 2, 3, 5, 8]` for `n=7`. Check below:

In [39]:
fibonacci_seq(17)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]